settings:
  title: 'Jumpstart Labs - Services We Use!'
  url: 'https://status.jumpstartlabs.co' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false  # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: cloudfloare-dns
    name: Cloudflare DNS
    url: 'https://1.1.1.1'
    method: GET
    expectStatus: 200
    followRedirect: true 
    
  - id: web05
    name: Webserver
    description: 'Main webserver for our static sites!'
    url: 'https://web05.baxtmann.me:2083'
    method: GET
    expectstatus: 200
   
  - id: box
    name: Mailserver
    description: 'General mailserver for JSL'
    url: 'https://box.baxtmann.me'
    method: GET
    expectstatus: 200
    
  - id: elastic
    name: Elasticsearch
    description: 'Main elastic endpoint'
    url: 'http://elastic.jumpstartlabs.co:5601'
    method: GET
    expectstatus: 200
    
  - id: noc
    name: NOC
    description: 'Check state of GNOC to confirm it is online'
    url: 'http://noc.baxtmann.me'
    method: GET
    expectstatus: 200
 
  - id: jira
    name: Jira
    description: 'Our Jira Instance'
    url: 'http://jumpstartlabs.atlassian.net'
    method: GET
    expectstatus: 200
    
  - id: confluence
    name: Confluence
    description: 'Our Confluence Instance'
    url: 'http://jumpstartlabs.atlassian.net'
    method: GET
    expectstatus: 200
 
  - id: zabbix
    name: Zabbix
    description: 'Zabbix Server - TODO'
    url: 'http://google.com'
    method: GET
    expectstatus: 200
 
  - id: grafana
    name: Grafana
    description: 'Grafana Server - TODO'
    url: 'http://google.com'
    method: GET
    expectstatus: 200
    followRedirect: true 
